--- #YAML:1.0
name:                Tie-Array-Packed
version:             0.09
abstract:            store arrays in memory efficiently as packed strings
license:             ~
author:              
    - Salvador Fandino <sfandino@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
